language: php

php:
    - 5.4
    - 5.5
    
install:
  - composer self-update
  - composer install
  
before_script:
    - mkdir build
    - mkdir build/logs
script:
    - phpunit --coverage-clover build/logs/clover.xml -c tests/phpunit.xml 
    
after_script:
    - php vendor/bin/coveralls

notifications:
    email: false