language: php

php:
    - 5.4
    - 5.5
    - hhvm
    
install:
  - composer self-update
  - composer install
  
before_script:
     - mkdir -p build/coverage
script:
    - cd tests
    - phpunit 
    
matrix:
  allow_failures:
    - php: hhvm