language: php

php:
    - 5.4
    - 5.5
    
install:
  - composer self-update
  - composer install
  
before_script:
     - cd tests
script:
    - phpunit 
    - php coverage-checker.php clover.xml 80
    
after_script:
    - php ../vendor/bin/coveralls
	
notifications:
    email: false