language: php

php:
    - 5.4
    - 5.5
    - hhvm
    
install:
  - composer self-update
  - composer install
  
before_script:
     - cd tests
script:
    - phpunit 
    
matrix:
  allow_failures:
    - php: hhvm