language: php

php:
    - 5.4.7
    - 5.4
    - 5.5
    - hhvm
    
install:
  - composer self-update
  - composer install
  
before_script:
     - mkdir -p build/coverage
     - cd tests
     
script:
    - phpunit 
    
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm